### ISSUE TITLE
Http Headers removed

### ISSUE THREAD

**Issue by deepcover96** [salsita/passthruapp#2]
Logging into Google or Amazon fail. (IE9)

The following headers are stripped from outgoing messages:
Accept-Language:
Content-Type:
Referer:

This is probably the cause of the failures.  These are the only ones that I noticed so far.  This should just pass the messages along I would presume, but the headers are getting stripped for some reason.  Not sure why.

I am just using the example: 
# include "APPSink.h"

STDMETHODIMP APPSink::BeginningTransaction( /\* [in] _/ LPCWSTR szURL, /_ [in] _/ LPCWSTR szHeaders, /_ [in] _/ DWORD dwReserved, /_ [out] */ LPWSTR *pszAdditionalHeaders )
{
   return S_OK;
}

STDMETHODIMP APPSink::OnResponse( /\* [in] _/ DWORD dwResponseCode, /_ [in] _/ LPCWSTR szResponseHeaders, /_ [in] _/ LPCWSTR szRequestHeaders, /_ [out] */ LPWSTR *pszAdditionalRequestHeaders )
{
   return S_OK;
}

STDMETHODIMP APPSink::ReportProgress( /\* [in] _/ ULONG ulStatusCode, /_ [in] */ LPCWSTR szStatusText )
{
   return S_OK;
}

**Comment by matthewgertner** [comment]
You need to call the default implementation of those methods. For `IHttpNegotiate` this means something like:

```
//  OnResponse
STDMETHODIMP CProtocolSink::OnResponse(
  /* [in] */ DWORD dwResponseCode,
  /* [in] */ LPCWSTR szResponseHeaders,
  /* [in] */ LPCWSTR szRequestHeaders,
  /* [out] */ LPWSTR *pszAdditionalRequestHeaders)
{
  HRESULT hr;
  CComPtr<IHttpNegotiate> spHttpNegotiate;
  QueryServiceFromClient(&spHttpNegotiate);

  if (pszAdditionalRequestHeaders)
  {
    *pszAdditionalRequestHeaders = 0;
  }

  hr = spHttpNegotiate ?
    spHttpNegotiate->OnResponse(dwResponseCode, szResponseHeaders,
      szRequestHeaders, pszAdditionalRequestHeaders) :
    S_OK;

  return hr;
}
```

For `IInternetProtocolSink`, in most cases I simply wouldn't implement this. If you have to for some reason, call the base class like this:

```
//  ReportProgress
STDMETHODIMP CProtocolSink::ReportProgress(
  /* [in] */ ULONG ulStatusCode,
  /* [in] */ LPCWSTR szStatusText)
{
  ATLASSERT(m_spInternetProtocolSink != 0);
  HRESULT hr = m_spInternetProtocolSink ?
    m_spInternetProtocolSink->ReportProgress(ulStatusCode, szStatusText) :
    S_OK;

  return hr;
}
```

I'll update the README when I get a chance.

**Comment by deepcover96** [comment]
Thanks so much for your response, it got me back on track.  The
IInternetProtocolSink was necessary to get redirects working.  I am having
an issue with "302 Moved Temporarily" responses.  I posted my question here:

http://social.msdn.microsoft.com/Forums/en-US/ieextensiondevelopment/thread/186d08e0-9053-4019-a59a-a40c1652414b

**Comment by deepcover96** [comment]
The issue I'm having now is when I try to log into Google, or any service where I'm redirected after a successful login, I am not redirected.  IE9 just shows that the page failed to load.  When I hit the back button I learn that the login attempt was successful and I have access to my account.  Logging in to web pages that do not redirect you (status 302), but instead returns a 200 OK response work fine.

Can you confirm that logging in to Google with the proper redirection works on this APP?
Thank you.

**Comment by matthewgertner** [comment]
I've never experienced this. Best is to post support requests to the MSDN forums where everyone can help out.
