### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by dodenko** [salsita/passthruapp#5]
Will this work with multiple browsers in the same thread?

**Comment by matthewgertner** [comment]
What do you mean by "multiple browsers"? Each process registers its own PAPP class factory if it wants to use it. I'm not sure what you mean by "same thread" either. Every request runs on a different thread.

**Comment by dodenko** [comment]
What if i have two browsers in same process? And i want to modify the requests. How to know whats coming from where?

**Comment by IUnknown68** [comment]
This is in deed a problem - you will know only for the document request, means, for the acutal page. In your implementing class you can use <code>QueryServiceFromClient(SID_SWebBrowserApp, ...)</code> to get the related webbrowser control. But there is no way as far as I know to get the webbrowser control for resources like images or style sheets.

The <code>QueryServiceFromClient</code> method also does not work always, and it depends when you call it if you will get the browser or not.

But there is another way: StartEx is called on the same thread where the webbrowser control initiated the request. You can use some global variable - or even better, a map threadID -> webbrowser control, to transport the current browser to the PAPP. Set the browser in an OnBeforeNavigate2 browser event, and then retrieve it in StartEx.

**Comment by dodenko** [comment]
Ah yes. This should work. I currently use just Start. :+1:

**Comment by IUnknown68** [comment]
Start or StartEx - depends on your IE version which one is used. To be sure you should handle both.

_Edit:_ <code>Start</code> or <code>StartEx</code> might be too early. I noticed that <code>BeginningTransaction</code> might be a better place.

Just try and play around a bit.

**Comment by dodenko** [comment]
In which versions is StartEX supported?

// After XP SP2

**Comment by dodenko** [comment]
StartEx is better because you dont have to deal with synchronization then.
