### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by dodenko** [salsita/passthruapp#6]
How can i add a custom header to the existing request headers. For Webbrowser control.

**Comment by IUnknown68** [comment]
Hi Dodenko, please checkout the <code>BeginningTransaction</code> method, it allows you to add your own headers.

**Comment by dodenko** [comment]
Do i have to call that method through QueryService ? Or does it get called by itself?

**Comment by IUnknown68** [comment]
You implement your own sink, derived from <code>PassthroughAPP::CInternetProtocolSinkWithSP</code>, and implement the method there. It then gets called from the protocol, and allows you add your headers. You should probably checkout the ancho code (https://github.com/salsita/ancho/tree/develop), that will answer a lot of your questions.

**Comment by dodenko** [comment]
Yes but will it work with custom header names? Such as "SomeHeader: SomeValue"

**Comment by matthewgertner** [comment]
Yes.
