### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by dodenko** [salsita/passthruapp#8]
Hello!

How can I get the request headers in the Start method? Aswell as how to set response headers in this method? 

Thanks

**Comment by matthewgertner** [comment]
You have to do that in BeginningTransaction. You can't set response headers at that point, of course, since the request hasn't been sent yet.

**Comment by dodenko** [comment]
Yes but I recreate the request with URL. I just return E_PENDING in Start Method. So when I get response headers I don't know where to set them to.
